#!/usr/bin/env bash
# Install and configure HAproxy on load balancing lb-01 server

# Update package lists before installing packages
sudo apt-get update

# Install required packages
sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get update
sudo apt-get -y --allow-downgrades install haproxy=2.0.*

# Append "ENABLED=1" to /etc/default/haproxy file
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy >/dev/null

# Create a new haproxy configuration file
new="listen appname
    bind 0.0.0.0:80
    mode http
    stats enable
    option httpclose
    option forwardfor
    server 140737-web-01 54.210.197.7:80 check
    server 140737-web-02 54.237.45.180:80 check"
echo "$new" | sudo tee /etc/haproxy/haproxy.cfg >/dev/null

# Restart the haproxy service
sudo systemctl restart haproxy.service
