#!/usr/bin/env bash
# Gets nginx running as nginx user and listening on 8080 on all active IPs
sudo pkill apache2
sudo sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 744 /etc/nginx/nginx.conf
sudo -u nginx nginx
